all:
	g++ -o Estera Estera_lim.cpp mrqmin.cpp mrqcof.cpp gaussj.cpp nrutil.cpp covsrt.cpp dpythag.cpp svdcmp.cpp svbksb.cpp Invmat.cpp -lm -I/usr/local/
debug:
	g++ -Wall -g -o Estera Estera_lim.cpp mrqmin.cpp mrqcof.cpp gaussj.cpp nrutil.cpp covsrt.cpp dpythag.cpp svdcmp.cpp svbksb.cpp Invmat.cpp -lm -I/usr/local/
